### ISSUE TITLE
Missing y-index in the page transition template

### ISSUE THREAD

**Issue by sajclarke** [HamedBahram/next-page-transition#1]
https://github.com/HamedBahram/next-page-transition/blob/eb43ac204aa5bdf94ac78a86eb56238c06c37dca/app/template.tsx#L8

There are missing parameters for the y-Index. This should be 
```
 initial={{ y: 20, opacity: 0 }}
 animate={{ y: 0, opacity: 1 }}
```

**Comment by HamedBahram** [comment]
This is just an example I demonstrated in the video. You can add any animation you want.
